export const lightColors = {
  background: '#f7f4fb',
  foreground: '#1d1330',
  card: '#ffffff',
  cardForeground: '#1d1330',
  popover: '#ffffff',
  popoverForeground: '#1d1330',
  primary: '#8f4ff5',
  primaryForeground: '#ffffff',
  secondary: '#efe7fb',
  secondaryForeground: '#4f4166',
  muted: '#f2ebfa',
  mutedForeground: '#7a6f8f',
  accent: '#eadcff',
  accentForeground: '#2f1b49',
  destructive: '#e6537f',
  destructiveForeground: '#ffffff',
  border: '#dcccf5',
  input: '#dcccf5',
  ring: '#8f4ff5',
} as const;

export const darkColors = {
  background: '#07040d',
  foreground: '#f5f1ff',
  card: '#140b20',
  cardForeground: '#f5f1ff',
  popover: '#12091f',
  popoverForeground: '#f5f1ff',
  primary: '#9b5cff',
  primaryForeground: '#ffffff',
  secondary: '#201133',
  secondaryForeground: '#d6caed',
  muted: '#110a19',
  mutedForeground: '#a59cb8',
  accent: '#25103d',
  accentForeground: '#f5f1ff',
  destructive: '#ff5c8d',
  destructiveForeground: '#ffffff',
  border: '#3a2359',
  input: '#311c4d',
  ring: '#9b5cff',
} as const;

export type TThemeColors = typeof lightColors;
